name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: ki502/flutter_web.github.io
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --web-renderer html
        # 1. change path which exist lib/main.dart
        working-directory: lib/main.dart
      - run: |
          # 2. change path to [existed lib/main.dart path]/build/web
          cd build/web
          git init
           # 3. change your email
          git config --global user.email ki502@naver.com
          # 4. change your name
          git config --global user.name ki502
          git status
          # 5. change your repository
          git remote add origin https://github.com/ki502/flutter_web.github.io
          git checkout -b master
          git add --all
          git commit -m "update"
          git push origin master -f